export const coachTour = [
  {
    id:    1,
    tab:   'home',
    action: null,
    title: 'Votre tableau de bord coach',
    body:  'Bienvenue ! En tant que coach, votre onglet Actus est votre cockpit : la carte "Avant-match" vous montre l\'état des convocations en temps réel, l\'entraînement du soir, et vous permet de lancer le live score.',
    emoji: '🎯',
    why:   'Toutes les infos de votre équipe accessibles en 1 tap — depuis le terrain ou les vestiaires.',
  },
  {
    id:     2,
    tab:    'mon-club',
    action: 'scroll-to-trainings',
    title:  'Gérer les entraînements',
    body:   'Planifiez et modifiez vos créneaux d\'entraînement. Chaque joueur reçoit un rappel automatique la veille. Les horaires sont toujours à jour pour toutes vos équipes.',
    emoji:  '🏃',
    why:    'Le rappel automatique réduit les absences non signalées de 45 %.',
  },
  {
    id:          3,
    tab:         'mon-club',
    action:      'open-convocations',
    title:       'Convoquer vos joueurs',
    body:        'Sélectionnez vos joueurs pour un match ou un tournoi en quelques secondes. Chaque convoqué reçoit une notification push et peut confirmer directement depuis son téléphone.',
    emoji:       '📋',
    target:      'convocations-tab',
    tryItAction: 'convocation-sent',
    tryItLabel:  'Envoyer une convocation',
    why:         '89 % des joueurs répondent à une convocation SportLink en moins de 4 heures.',
  },
  {
    id:     4,
    tab:    'home',
    action: null,
    title:  'Suivi des présences en direct',
    body:   'Dès qu\'un joueur répond, le compteur se met à jour : X Présents / Y Absents / Z Sans réponse. Un bouton "Relancer" envoie un rappel push aux joueurs qui n\'ont pas encore répondu.',
    emoji:  '✅',
    why:    'Vous composez votre équipe et préparez votre tactique 48h avant le coup d\'envoi.',
  },
  {
    id:          5,
    tab:         'mon-club',
    action:      'open-announcements',
    title:       'Communiquer avec l\'équipe',
    body:        'Envoyez des messages ciblés à votre équipe : consignes tactiques, rappels, infos de dernière minute. Vos joueurs les reçoivent en notification push instantanée.',
    emoji:       '💬',
    tryItAction: 'announcement-sent',
    tryItLabel:  'Envoyer un message',
    why:         'Un message de préparation la veille améliore la ponctualité de 30 % en moyenne.',
  },
  {
    id:    6,
    tab:   'mon-club',
    action: null,
    title: 'Rejoignez SportLink',
    body:  'Simplifiez votre quotidien de coach. Créez votre club gratuitement et gérez toute votre équipe depuis une seule application — convocations, présences, communication.',
    emoji: '🚀',
    isCTA: true,
  },
];
