// Tour Coach — 8 étapes
// Multiplex et score live AVANT l'annonce (qui navigue vers Mon Club)
// pour éviter les sauts de tab non guidés.

export const coachTour = [
  {
    id:    1,
    title: 'Votre cockpit coach',
    body:  'Vous êtes sur l\'écran principal. En haut : la séance d\'entraînement de ce soir. Dessous : la carte match avec l\'état des convocations. Tout sans ouvrir 4 applications.',
    emoji: '🎯',
    tip:   'Le guide reste visible. Réduisez-le (▼) pour naviguer librement, agrandissez-le (▲) pour le relire.',
    why:   'Les coachs SportLink passent 70% moins de temps sur la logistique.',
  },
  {
    id:          2,
    title:       'Convoquez votre équipe',
    body:        'Appuyez sur "Créer la convocation" visible sur la carte match. Sélectionnez vos joueurs, validez. Chaque joueur reçoit une notification push instantanément.',
    emoji:       '📋',
    clickTarget: 'convocation-btn',
    clickLabel:  '"Créer la convocation" sur la carte match',
    tryItAction: 'convocation-sent',
    tryItLabel:  'Envoyer la convocation',
    why:         '89% de taux de réponse vs 60% par WhatsApp.',
  },
  {
    id:          3,
    title:       'Suivez les réponses en direct',
    body:        'Dès qu\'un joueur répond, la carte match se met à jour : présents, absents, en attente. Appuyez sur la carte pour voir l\'état complet de votre effectif.',
    emoji:       '✅',
    clickTarget: 'coach-match-card',
    clickLabel:  'Carte match pour voir les réponses',
    closeOverlayBefore: true,
    tip:         'Composez tactiquement 48h à l\'avance grâce aux réponses en temps réel.',
    why:         'Connaître son effectif à l\'avance améliore la préparation tactique.',
  },
  {
    id:          4,
    title:       'Saisissez le score en direct',
    body:        'Pendant le match, appuyez sur le pupitre de score visible à l\'écran. Mettez à jour but après but. Supporters et président voient le résultat s\'actualiser en temps réel.',
    emoji:       '🔴',
    clickTarget: 'live-score-pupitre',
    clickLabel:  'Pupitre de score live',
    why:         'Le score en direct augmente l\'engagement des supporters de 3×.',
  },
  {
    id:          5,
    title:       'Tous vos matchs simultanément',
    body:        'Appuyez sur la section Multiplex pour voir l\'Équipe 1, la Réserve, l\'U17 et les Féminines simultanément. Scores mis à jour en direct sans rafraîchir.',
    emoji:       '📡',
    clickTarget: 'live-multiplex',
    clickLabel:  'Section Multiplex des scores live',
    why:         'Pilotez plusieurs équipes en même temps, depuis n\'importe où.',
  },
  {
    id:          6,
    title:       'Envoyez un briefing à votre équipe',
    body:        'Appuyez sur + en bas au centre. Le menu d\'actions s\'ouvre. Sélectionnez ensuite "Envoyer une annonce".',
    emoji:       '➕',
    clickTarget: 'fab-add',
    clickLabel:  'Bouton + au centre de la barre en bas',
    closeOverlayBefore: true,
  },
  {
    id:          7,
    title:       'Rédigez et envoyez le message',
    body:        'Tapez sur "Envoyer une annonce". La page Mon Club s\'ouvre avec le formulaire. Rédigez votre briefing pré-match, bilan d\'entraînement ou consignes tactiques. Envoyez.',
    emoji:       '📣',
    clickTarget: 'fab-announce',
    clickLabel:  '"Envoyer une annonce" dans le menu',
    tryItAction: 'announcement-sent',
    tryItLabel:  'Envoyer le message',
    why:         'La communication ciblée renforce la cohésion et l\'engagement des joueurs.',
  },
  {
    id:    8,
    title: 'Gérez votre équipe comme un pro',
    body:  'Convocations, scores live, communication — tout en un. Créez votre espace coach gratuitement en 2 minutes.',
    emoji: '⚽',
    isCTA: true,
  },
];
