export const coachTour = [
  {
    id:    1,
    title: 'Votre espace coach',
    body:  'La séance d\'entraînement de ce soir s\'affiche en haut. En dessous, la carte match montre l\'état des convocations. Tout sans ouvrir 4 applications différentes.',
    emoji: '🎯',
    tip:   'Ce guide reste visible en tout moment. Réduisez-le en bulle pour naviguer librement.',
    why:   'Les coachs SportLink passent 70% moins de temps à gérer la logistique.',
  },
  {
    id:          2,
    title:       'Convoquez votre équipe',
    body:        'Sur la carte match visible à l\'écran, appuyez sur "Créer la convocation". Sélectionnez les joueurs et validez — chaque joueur reçoit une notification push instantanément.',
    emoji:       '📋',
    clickTarget: 'convocation-btn',
    clickLabel:  '"Créer la convocation" sur la carte match',
    tryItAction: 'convocation-sent',
    tryItLabel:  'Envoyer une convocation',
    why:         '89% de taux de réponse aux convocations vs 60% par WhatsApp.',
  },
  {
    id:          3,
    title:       'Les réponses arrivent en direct',
    body:        'Dès qu\'un joueur répond, la carte match se met à jour : X présents, Y absents, Z en attente. Voici ce que vous voyez après l\'envoi de la convocation. Regardez la carte.',
    emoji:       '✅',
    clickTarget: 'coach-match-card',
    clickLabel:  'Carte match pour voir les réponses',
    closeOverlayBefore: true,
    tip:         'Composez tactiquement 48h à l\'avance grâce aux réponses en temps réel.',
    why:         'Connaître son effectif à l\'avance améliore la préparation tactique et réduit le stress.',
  },
  {
    id:          4,
    title:       'Saisissez le score en direct',
    body:        'Depuis le pupitre de score visible à l\'écran, appuyez dessus pour mettre à jour le score but après but. Supporters et présidents voient le résultat s\'actualiser en temps réel.',
    emoji:       '🔴',
    clickTarget: 'live-score-pupitre',
    clickLabel:  'Pupitre de score live',
    why:         'Le score en direct augmente l\'engagement des supporters de 3× pendant un match.',
  },
  {
    id:          5,
    title:       'Envoyez un message à l\'équipe',
    body:        'Appuyez sur + en bas au centre pour ouvrir le menu d\'actions. Vous pouvez envoyer un briefing pré-match, un bilan d\'entraînement ou des consignes tactiques.',
    emoji:       '📣',
    clickTarget: 'fab-add',
    clickLabel:  'Bouton + en bas au centre',
    closeOverlayBefore: true,
  },
  {
    id:          6,
    title:       'Choisissez "Envoyer une annonce"',
    body:        'Sélectionnez "Envoyer une annonce", rédigez votre message d\'équipe (briefing, bilan, consignes) et envoyez. Vos joueurs le reçoivent en push en quelques secondes.',
    emoji:       '📣',
    clickTarget: 'fab-announce',
    clickLabel:  '"Envoyer une annonce" dans le menu',
    tryItAction: 'announcement-sent',
    tryItLabel:  'Envoyer un message à l\'équipe',
    why:         'La communication ciblée renforce la cohésion et l\'engagement des joueurs.',
  },
  {
    id:          7,
    title:       'Tous vos matchs simultanément',
    body:        'La section Multiplex affiche tous les matchs de vos équipes en cours. Appuyez sur la section pour voir les scores en direct de l\'Équipe 1, la Réserve, l\'U17 et les Féminines.',
    emoji:       '📡',
    clickTarget: 'live-multiplex',
    clickLabel:  'Section Multiplex des scores live',
    why:         'Un coach peut piloter plusieurs équipes en même temps, depuis n\'importe où.',
  },
  {
    id:    8,
    title: 'Gérez votre équipe comme un pro',
    body:  'Convocations, communication, scores live — tout en un. Créez votre espace coach gratuitement en 2 minutes.',
    emoji: '⚽',
    isCTA: true,
  },
];
