// Tour Communication — 6 étapes
// Annonce (navigue vers Mon Club) puis navigation vers Clubs depuis Mon Club.

export const communicationTour = [
  {
    id:    1,
    title: 'Votre atelier communication',
    body:  'Vous êtes sur l\'accueil : fil d\'actualité du club, scores en direct, annonces récentes. C\'est aussi depuis ici que vous publiez. Faites défiler pour voir tout ce que SportLink affiche automatiquement.',
    emoji: '📣',
    tip:   'Le guide reste visible. Réduisez-le (▼) pour naviguer librement, agrandissez-le (▲) pour le relire.',
    why:   'Les clubs avec une communication régulière ont 3× plus d\'engagement en ligne.',
  },
  {
    id:          2,
    title:       'Ouvrez le menu d\'actions',
    body:        'Appuyez sur le bouton + au centre de la barre en bas. Le menu d\'actions s\'ouvre avec toutes les options de publication disponibles.',
    emoji:       '➕',
    clickTarget: 'fab-add',
    clickLabel:  'Bouton + au centre de la barre en bas',
  },
  {
    id:          3,
    title:       'Publiez une annonce percutante',
    body:        'Tapez sur "Envoyer une annonce". La page Mon Club s\'ouvre. Choisissez le type (résultat, info, urgence), rédigez votre message et envoyez. 85% de taux d\'ouverture.',
    emoji:       '📢',
    clickTarget: 'fab-announce',
    clickLabel:  '"Envoyer une annonce" dans le menu',
    tryItAction: 'announcement-sent',
    tryItLabel:  'Publier l\'annonce',
    why:         'Les annonces push ont 85% de taux d\'ouverture vs 20% pour les emails.',
  },
  {
    id:          4,
    title:       'Découvrez votre vitrine publique',
    body:        'Appuyez sur l\'onglet "Clubs" en bas à droite. C\'est la page que vos supporters, partenaires et futurs membres découvrent. Agenda, résultats, sponsors — sans aucune compétence web.',
    emoji:       '🌐',
    clickTarget: 'tab-clubs',
    clickLabel:  'Onglet "Clubs" en bas à droite',
    closeOverlayBefore: true,
    why:         'Une page club soignée augmente les abonnements spontanés de 60%.',
  },
  {
    id:          5,
    title:       'Abonnez-vous pour tester le flux',
    body:        'Appuyez sur un club dans la liste pour ouvrir sa page. Puis appuyez sur "Suivre" — vos fans reçoivent ensuite chaque annonce, résultat et actualité en notification push.',
    emoji:       '🔔',
    clickTarget: 'follow-club-btn',
    clickLabel:  'Bouton "Suivre" sur la page du club (ouvrez d\'abord un club de la liste)',
    tryItAction: 'club-followed',
    tryItLabel:  'Suivre le club',
    why:         'Les abonnés sont 3× plus fidèles et plus engagés que les non-abonnés.',
  },
  {
    id:    6,
    title: 'Transformez la communication de votre club',
    body:  'Annonces push, page club pro, scores en direct — tout en un. Créez votre espace communication gratuitement en 2 minutes.',
    emoji: '📣',
    isCTA: true,
  },
];
