export const communicationTour = [
  {
    id:          1,
    tab:         'home',
    action:      'open-poster-studio',
    title:       'Votre atelier affiches pro',
    body:        '37 templates professionnels, 3 formats (story Instagram, carré, paysage). Choisissez, personnalisez les couleurs, le texte et les logos. Exportez en HD en 2 minutes.',
    emoji:       '🎨',
    tryItAction: 'poster-generated',
    tryItLabel:  'Créer et télécharger une affiche',
    why:         'Les clubs avec des affiches pro gagnent 40% d\'abonnés en plus sur Instagram.',
  },
  {
    id:     2,
    tab:    'home',
    action: 'close-overlay',
    title:  'Partager sur tous les réseaux',
    body:   'Depuis PosterStudio, partagez en un tap sur WhatsApp, Instagram et Facebook. Votre affiche touche directement les supporters, parents et futurs abonnés.',
    emoji:  '📱',
    why:    'Un partage WhatsApp touche en moyenne 150 contacts dans un réseau de supporters local.',
  },
  {
    id:          3,
    tab:         'home',
    action:      'open-announcements',
    title:       'Publier des annonces percutantes',
    body:        'Résultats de match, convocations urgentes, infos pratiques. Ciblage par équipe, push garanti. Taux d\'ouverture 85% vs 20% pour les emails.',
    emoji:       '📢',
    tryItAction: 'announcement-sent',
    tryItLabel:  'Publier une annonce',
    why:         'La communication régulière fidélise les supporters et augmente l\'engagement.',
  },
  {
    id:     4,
    tab:    'clubs',
    action: null,
    title:  'La vitrine publique du club',
    body:   'C\'est ce que voient vos supporters, partenaires et futurs membres. Agenda, résultats, sponsors, effectif — sans aucune compétence web requise.',
    emoji:  '🌐',
    why:    'Une page club soignée augmente les abonnements spontanés de 60%.',
  },
  {
    id:    5,
    tab:   'home',
    action: null,
    title: 'Rejoignez SportLink',
    body:  'Transformez la communication de votre club. Affiches pro, annonces push, page club — tout en un.',
    emoji: '📣',
    isCTA: true,
  },
];
