export const communicationTour = [
  {
    id:     1,
    tab:    'mon-club',
    action: null,
    title:  'Votre espace communication',
    body:   'SportLink transforme la communication de votre club. Affiches pro, annonces ciblées, réseaux sociaux — tout depuis une seule interface.',
    emoji:  '📣',
  },
  {
    id:     2,
    tab:    'mon-club',
    action: 'open-poster-studio',
    title:  'PosterStudio',
    body:   'Créez des affiches professionnelles pour vos matchs et tournois. 37 templates, 3 formats (story, carré, paysage). Personnalisables aux couleurs de votre club.',
    emoji:  '🎨',
  },
  {
    id:     3,
    tab:    'mon-club',
    action: 'close-overlay',
    title:  'Personnaliser votre affiche',
    body:   'Modifiez les couleurs, polices, logos et photos en quelques clics. Le PosterStudio adapte automatiquement le design à l\'identité visuelle de votre club.',
    emoji:  '✏️',
  },
  {
    id:     4,
    tab:    'mon-club',
    action: 'open-announcements',
    title:  'Publier des annonces',
    body:   'Résultats, convocations, informations pratiques. 13 templates d\'annonces prêts à l\'emploi, ciblables par équipe, avec envoi immédiat ou programmé.',
    emoji:  '📢',
  },
  {
    id:     5,
    tab:    'mon-club',
    action: 'close-overlay',
    title:  'Sponsors et partenaires',
    body:   'Valorisez vos sponsors directement dans l\'application. Leur logo et leur message apparaissent dans le fil d\'actualité de vos abonnés.',
    emoji:  '🤝',
  },
  {
    id:     6,
    tab:    'mon-club',
    action: null,
    title:  'Révolutionnez votre com',
    body:   'Créez votre club gratuitement et donnez à votre club une image professionnelle qui attire de nouveaux membres et partenaires.',
    emoji:  '🚀',
    isCTA:  true,
  },
];
