export const communicationTour = [
  {
    id:          1,
    title:       'Votre atelier communication',
    body:        'Annonces push, page club, affiches pro — tout ce dont un responsable communication a besoin pour amplifier la présence de son club.',
    emoji:       '📣',
    why:         'Les clubs avec une communication régulière ont 3× plus d\'engagement en ligne.',
  },
  {
    id:          2,
    title:       'Publiez une annonce percutante',
    body:        'Appuyez sur + pour accéder à la création d\'annonce. Résultats de match, convocations urgentes, infos pratiques — ciblées par équipe avec push garanti.',
    emoji:       '📢',
    clickTarget: 'fab-add',
    clickLabel:  'Bouton + en bas au centre',
  },
  {
    id:          3,
    title:       'Choisissez "Envoyer une annonce"',
    body:        'Sélectionnez le type d\'annonce, rédigez votre message et envoyez. 85% de taux d\'ouverture — vs 20% pour les emails.',
    emoji:       '📢',
    clickTarget: 'fab-announce',
    clickLabel:  '"Envoyer une annonce"',
    tryItAction: 'announcement-sent',
    tryItLabel:  'Publier une annonce',
    why:         'La communication régulière fidélise les supporters et augmente l\'engagement.',
  },
  {
    id:          4,
    title:       'Découvrez la page publique du club',
    body:        'Naviguez vers l\'onglet Clubs pour voir la vitrine que vos supporters, partenaires et futurs membres découvrent.',
    emoji:       '🌐',
    clickTarget: 'tab-clubs',
    clickLabel:  'Onglet "Clubs"',
    closeOverlayBefore: true,
  },
  {
    id:          5,
    title:       'Votre vitrine professionnelle',
    body:        'Agenda, résultats, sponsors, effectif — sans aucune compétence web requise. Une page soignée augmente les abonnements spontanés de 60%.',
    emoji:       '🌐',
    why:         'Une page club soignée augmente les abonnements spontanés de 60%.',
  },
  {
    id:          6,
    title:       'Transformez la communication de votre club',
    body:        'Affiches pro, annonces push, page club — tout en un. Créez votre espace communication gratuitement en 2 minutes.',
    emoji:       '📣',
    isCTA:       true,
  },
];
