export const parentTour = [
  {
    id:    1,
    tab:   'home',
    action: null,
    title: 'Tout le club de vos enfants, en un écran',
    body:  'L\'onglet Actus affiche tout en un scroll. Zone 1 : les convocations en attente — Liam Creach (U17 vs US Bohars) et Noa Kerguelen (Tournoi de la Pentecôte) vous attendent. Zone 2 : FC SportLink Démo U17 mène 2-0 EN DIRECT. Zone 3 : les dernières annonces du club.',
    emoji: '👨‍👧',
    why:   'Les parents reçoivent l\'info du club 3× plus vite qu\'avec les groupes WhatsApp.',
  },
  {
    id:          2,
    tab:         'home',
    action:      null,
    title:       'Convocation & transport en 3 taps',
    body:        'Votre enfant est convoqué ! Appuyez sur [Présent] — un panneau s\'ouvre avec 3 choix : "🚗 Je conduis (+ X places)" pour créer un trajet partagé, "🙋 Je cherche une place" pour être mis en attente, ou "🏡 Par mes propres moyens" pour sortir des calculs. Le coach voit votre réponse et la logistique en temps réel.',
    emoji:       '📋',
    target:      'convocation-respond',
    tryItAction: 'convocation-responded',
    tryItLabel:  'Répondre à la convocation',
    why:         'Le coach voit votre réponse et la logistique de transport instantanément — il peut composer son équipe 48h à l\'avance.',
  },
  {
    id:     3,
    tab:    'home',
    action: null,
    title:  'Le covoiturage sans effort',
    body:   'Si vous avez sélectionné "Je conduis", un trajet est créé automatiquement et apparaît dans le fil (Zone 3) pour les autres parents. Plus besoin de SMS : tout le monde voit les places disponibles en temps réel.',
    emoji:  '🚗',
    why:    'Le covoiturage réduit les coûts de transport et renforce le lien entre familles du club.',
  },
  {
    id:       4,
    tab:      'map',
    action:   'focus-demo-event',
    position: 'top',
    title:    'Trouver le lieu du match',
    body:     'Chaque événement est géolocalisé. Retrouvez en un tap l\'adresse exacte du stade, visualisez l\'itinéraire et arrivez à l\'heure — même pour un terrain que vous n\'avez jamais visité.',
    emoji:    '📍',
    why:      'Fini les recherches Google "stade de..." — l\'adresse exacte est dans SportLink.',
  },
  {
    id:          5,
    tab:         'home',
    action:      null,
    title:       'Sauvegarder les matchs',
    body:        'Ajoutez les matchs de votre enfant en favoris. Vous recevrez un rappel automatique la veille et le jour J — ne ratez plus jamais un match important.',
    emoji:       '⭐',
    target:      'favorite-btn',
    tryItAction: 'event-favorited',
    tryItLabel:  'Sauvegarder un événement',
    why:         'Les rappels automatiques réduisent les oublis de 80 % d\'après nos utilisateurs.',
  },
  {
    id:    6,
    tab:   'home',
    action: null,
    title: 'Rejoignez SportLink',
    body:  'Créez votre compte gratuitement et restez connecté à l\'actualité sportive de vos enfants. Simple, rapide, efficace — et zéro groupe WhatsApp à gérer.',
    emoji: '🚀',
    isCTA: true,
  },
];
