// Tour Parent — 7 étapes
// Tout sur l'onglet Accueil puis navigation vers Clubs.

export const parentTour = [
  {
    id:    1,
    title: 'Tout le club depuis votre canapé',
    body:  'Vous êtes sur l\'écran principal. En haut : la convocation de votre enfant pour le prochain match. En dessous : les annonces du club et les scores en direct. Tout sans chercher sur 5 groupes WhatsApp.',
    emoji: '👨‍👧',
    tip:   'Le guide reste visible. Réduisez-le (▼) pour naviguer librement, agrandissez-le (▲) pour le relire.',
    why:   'Les parents SportLink passent 80% moins de temps à chercher les infos du club.',
  },
  {
    id:          2,
    title:       'Répondez à la convocation',
    body:        'Votre enfant est convoqué pour le match. Appuyez sur "Présent", "Absent" ou "Indisponible" sur la carte de convocation. Le coach voit votre réponse instantanément.',
    emoji:       '📲',
    clickTarget: 'convocation-respond',
    clickLabel:  'Boutons Présent / Absent / Indisponible (onglet Agenda)',
    onTab:       'Agenda',
    tryItAction: 'convocation-responded',
    tryItLabel:  'Répondre à la convocation',
    why:         'Les convocations SportLink ont 89% de taux de réponse vs 60% par WhatsApp.',
  },
  {
    id:          3,
    title:       'Organisez le covoiturage en 2 taps',
    body:        'Un covoiturage est disponible pour ce match. Appuyez sur la carte de covoiturage pour demander une place ou voir les détails du trajet. Zéro message à envoyer.',
    emoji:       '🚗',
    clickTarget: 'carpool-card',
    clickLabel:  'Carte de covoiturage sur l\'écran',
    tryItAction: 'carpool-requested',
    tryItLabel:  'Demander une place',
    closeOverlayBefore: true,
    tip:         'Proposez aussi vos places en créant votre propre trajet depuis ce même menu.',
    why:         'Le covoiturage intégré réduit les retards de 35% et renforce la cohésion.',
  },
  {
    id:          4,
    title:       'Sauvegardez les matchs importants',
    body:        'Appuyez sur l\'étoile ⭐ sur la carte d\'un match pour le sauvegarder. Vous recevrez un rappel automatique la veille et le jour J. Plus jamais de match raté.',
    emoji:       '⭐',
    clickTarget: 'favorite-btn',
    clickLabel:  'Étoile ⭐ sur une carte match',
    tryItAction: 'event-favorited',
    tryItLabel:  'Sauvegarder le match',
    closeOverlayBefore: true,
    why:         'Les parents qui sauvegardent les matchs assistent à 2× plus de rencontres.',
  },
  {
    id:          5,
    title:       'Découvrez la page complète du club',
    body:        'Appuyez sur l\'onglet "Clubs" en bas à droite. Vous accédez à la vitrine du club de votre enfant : agenda complet, résultats, effectif et sponsors.',
    emoji:       '🏆',
    clickTarget: 'tab-clubs',
    clickLabel:  'Onglet "Clubs" en bas à droite',
    closeOverlayBefore: true,
  },
  {
    id:          6,
    title:       'Abonnez-vous pour tout recevoir',
    body:        'Appuyez sur un club dans la liste pour ouvrir sa page. Puis appuyez sur "Suivre". Vous recevrez chaque résultat, annonce et convocation urgente en notification push. Zéro risque de rater une info.',
    emoji:       '🔔',
    clickTarget: 'follow-club-btn',
    clickLabel:  'Bouton "Suivre" sur la page du club (ouvrez d\'abord un club de la liste)',
    tryItAction: 'club-followed',
    tryItLabel:  'Suivre le club',
    why:         'Les abonnés reçoivent les informations 3× plus vite que les non-abonnés.',
  },
  {
    id:    7,
    title: 'Ne manquez plus rien',
    body:  'Convocations, covoiturage, matchs sauvegardés, annonces push — tout gratuit. Créez votre compte en 30 secondes.',
    emoji: '👨‍👧‍👦',
    isCTA: true,
  },
];
