export const parentTour = [
  {
    id:    1,
    tab:   'home',
    action: null,
    title: 'Votre fil d\'actualité',
    body:  'Suivez les clubs de vos enfants en temps réel. Résultats, annonces, matchs à venir : tout ce qui concerne votre enfant apparaît ici, dans un seul endroit.',
    emoji: '👨‍👧',
    why:   'Les parents reçoivent l\'info du club 3× plus vite qu\'avec les groupes WhatsApp.',
  },
  {
    id:          2,
    tab:         'home',
    action:      null,
    title:       'Convocation & logistique en un geste',
    body:        'Votre enfant est convoqué pour un match ! Appuyez sur "Accepter" — l\'application vous demande ensuite si vous conduisez, cherchez une place, ou venez par vos propres moyens. En un tap, tout est coordonné.',
    emoji:       '📋',
    target:      'convocation-respond',
    tryItAction: 'convocation-responded',
    tryItLabel:  'Répondre à la convocation',
    why:         'Le coach voit votre réponse et la logistique de transport instantanément — il peut composer son équipe 48h à l\'avance.',
  },
  {
    id:     3,
    tab:    'home',
    action: null,
    title:  'Le covoiturage automatique',
    body:   'Si vous avez dit "Je conduis", un trajet est automatiquement créé. Les autres parents le voient et peuvent réserver une place. Fini les SMS dans tous les sens pour organiser le transport !',
    emoji:  '🚗',
    why:    'Le covoiturage réduit les coûts de transport et renforce le lien entre familles du club.',
  },
  {
    id:       4,
    tab:      'map',
    action:   'focus-demo-event',
    position: 'top',
    title:    'Trouver le lieu du match',
    body:     'Chaque événement est géolocalisé. Retrouvez en un tap l\'adresse exacte du stade, visualisez l\'itinéraire et arrivez à l\'heure — même pour un terrain que vous n\'avez jamais visité.',
    emoji:    '📍',
    why:      'Fini les recherches Google "stade de..." — l\'adresse exacte est dans SportLink.',
  },
  {
    id:          5,
    tab:         'home',
    action:      null,
    title:       'Sauvegarder les matchs',
    body:        'Ajoutez les matchs de votre enfant en favoris. Vous recevrez un rappel automatique la veille et le jour J — ne ratez plus jamais un match important.',
    emoji:       '⭐',
    target:      'favorite-btn',
    tryItAction: 'event-favorited',
    tryItLabel:  'Sauvegarder un événement',
    why:         'Les rappels automatiques réduisent les oublis de 80 % d\'après nos utilisateurs.',
  },
  {
    id:    6,
    tab:   'home',
    action: null,
    title: 'Rejoignez SportLink',
    body:  'Créez votre compte gratuitement et restez connecté à l\'actualité sportive de vos enfants. Simple, rapide, efficace — et zéro groupe WhatsApp à gérer.',
    emoji: '🚀',
    isCTA: true,
  },
];
