export const parentTour = [
  {
    id:    1,
    tab:   'home',
    action: null,
    title: 'Votre fil d\'actualité',
    body:  'Suivez les clubs de vos enfants en temps réel. Résultats, annonces, matchs à venir : tout ce qui concerne votre enfant apparaît ici.',
    emoji: '👨‍👧',
    why:   'Les parents reçoivent l\'info du club 3× plus vite qu\'avec les groupes WhatsApp.',
  },
  {
    id:          2,
    tab:         'home',
    action:      null,
    title:       'Les convocations',
    body:        'Votre enfant est convoqué ? Vous recevez une notification push immédiatement. Confirmez la présence en un tap depuis l\'application.',
    emoji:       '📋',
    target:      'convocation-respond',
    tryItAction: 'convocation-responded',
    tryItLabel:  'Répondre à la convocation',
    why:         'Le coach reçoit votre réponse instantanément et peut adapter sa liste en temps réel.',
  },
  {
    id:       3,
    tab:      'map',
    action:   'focus-demo-event',
    position: 'top',
    title:    'Trouver le lieu du match',
    body:     'Chaque événement est géolocalisé. Trouvez facilement le stade, visualisez l\'itinéraire et arrivez à l\'heure le jour du match.',
    emoji:    '📍',
    why:      'Fini les recherches Google "stade de..." — l\'adresse exacte est dans SportLink.',
  },
  {
    id:     4,
    tab:    'map',
    action: 'focus-demo-event',
    title:  'Organiser le covoiturage',
    body:   'Proposez ou demandez un covoiturage pour les déplacements. Coordonnez le transport avec les autres parents de l\'équipe en quelques secondes.',
    emoji:  '🚗',
    why:    'Le covoiturage réduit les coûts de transport et renforce le lien entre familles.',
  },
  {
    id:          5,
    tab:         'home',
    action:      null,
    title:       'Sauvegarder les matchs',
    body:        'Ajoutez les matchs de vos enfants en favoris. Recevez des rappels la veille et le jour J pour ne jamais rater un événement important.',
    emoji:       '⭐',
    target:      'favorite-btn',
    tryItAction: 'event-favorited',
    tryItLabel:  'Sauvegarder un événement',
    why:         'Les rappels automatiques réduisent les oublis de 80 % d\'après nos utilisateurs.',
  },
  {
    id:    6,
    tab:   'home',
    action: null,
    title: 'Rejoignez SportLink',
    body:  'Créez votre compte gratuitement et restez connecté à l\'actualité sportive de vos enfants. Simple, rapide, efficace.',
    emoji: '🚀',
    isCTA: true,
  },
];
