export const playerTour = [
  {
    id:    1,
    title: 'Votre espace joueur',
    body:  'Vos convocations arrivent directement ici. Plus besoin d\'attendre un SMS ou un groupe WhatsApp surchargé — regardez la convocation affichée sur cet écran.',
    emoji: '⚽',
    tip:   'Ce guide reste visible à tout moment. Appuyez sur la bulle pour le rouvrir si vous l\'avez réduit.',
    why:   'Les joueurs SportLink ne manquent plus jamais une convocation.',
  },
  {
    id:          2,
    title:       'Répondez à votre convocation',
    body:        'Présent, absent ou indisponible ? Appuyez sur le bouton correspondant sur la carte de convocation. Votre coach voit votre réponse instantanément et peut composer son équipe 48h à l\'avance.',
    emoji:       '✅',
    clickTarget: 'convocation-respond',
    clickLabel:  'Boutons Présent / Absent / Indisponible',
    tryItAction: 'convocation-responded',
    tryItLabel:  'Répondre à la convocation',
    why:         'Un taux de réponse élevé permet au coach de mieux préparer les matchs collectivement.',
  },
  {
    id:          3,
    title:       'Organisez votre transport',
    body:        'Un covoiturage est disponible pour ce déplacement. Appuyez sur la carte de covoiturage pour rejoindre un trajet. Zéro message WhatsApp nécessaire.',
    emoji:       '🚗',
    clickTarget: 'carpool-card',
    clickLabel:  'Carte de covoiturage',
    tryItAction: 'carpool-requested',
    tryItLabel:  'Demander une place',
    closeOverlayBefore: true,
    why:         'Le covoiturage intégré réduit les retards et renforce la cohésion d\'équipe.',
  },
  {
    id:          4,
    title:       'Sauvegardez vos matchs',
    body:        'Appuyez sur l\'étoile ⭐ sur la carte d\'un événement pour recevoir un rappel la veille. Suivez aussi les autres équipes du club depuis le même endroit.',
    emoji:       '⭐',
    clickTarget: 'favorite-btn',
    clickLabel:  'Étoile ⭐ sur la carte match',
    tryItAction: 'event-favorited',
    tryItLabel:  'Ajouter un match aux favoris',
    closeOverlayBefore: true,
    why:         'Les joueurs qui suivent l\'ensemble du club sont 2× plus engagés dans la vie associative.',
  },
  {
    id:          5,
    title:       'Tous les matchs du club en direct',
    body:        'Appuyez sur la section Multiplex pour voir les scores en direct de toutes les équipes — même pendant votre propre match depuis la mi-temps.',
    emoji:       '📡',
    clickTarget: 'live-multiplex',
    clickLabel:  'Section Multiplex des scores live',
    why:         'Rester connecté à son club renforce l\'appartenance et la motivation.',
  },
  {
    id:    6,
    title: 'Rejoignez SportLink',
    body:  'Convocations, transport, résultats — gérez tout en un tap. Créez votre compte gratuitement.',
    emoji: '⚽',
    isCTA: true,
  },
];
