export const playerTour = [
  {
    id:          1,
    title:       'Votre espace joueur',
    body:        'Vos convocations arrivent directement ici. Plus besoin d\'attendre un SMS ou un groupe WhatsApp surchargé — répondez en 2 taps.',
    emoji:       '⚽',
    why:         'Les joueurs SportLink ne manquent plus jamais une convocation.',
  },
  {
    id:          2,
    title:       'Répondez à votre convocation',
    body:        'Présent, absent ? Indisponible ? Appuyez sur le bouton correspondant. Votre coach voit votre réponse instantanément et peut composer son équipe 48h à l\'avance.',
    emoji:       '✅',
    clickTarget: 'convocation-respond',
    clickLabel:  'Boutons de réponse convocation',
    tryItAction: 'convocation-responded',
    tryItLabel:  'Répondre à la convocation',
    why:         'Un taux de réponse élevé permet de mieux préparer les matchs collectivement.',
  },
  {
    id:          3,
    title:       'Organisez votre transport',
    body:        'Besoin d\'un covoiturage pour le déplacement ? Appuyez sur la carte pour rejoindre un trajet disponible. Zéro message WhatsApp.',
    emoji:       '🚗',
    clickTarget: 'carpool-card',
    clickLabel:  'Carte covoiturage',
    tryItAction: 'carpool-requested',
    tryItLabel:  'Demander une place',
    why:         'Le covoiturage intégré réduit les retards et renforce la cohésion d\'équipe.',
    closeOverlayBefore: true,
  },
  {
    id:          4,
    title:       'Sauvegardez vos matchs',
    body:        'Appuyez sur l\'étoile ⭐ pour sauvegarder un match et recevoir un rappel la veille. Suivez aussi les autres équipes du club.',
    emoji:       '⭐',
    clickTarget: 'favorite-btn',
    clickLabel:  'Étoile ⭐ du match',
    tryItAction: 'event-favorited',
    tryItLabel:  'Ajouter un match aux favoris',
    why:         'Les joueurs qui suivent l\'ensemble du club sont 2× plus engagés dans la vie associative.',
    closeOverlayBefore: true,
  },
  {
    id:          5,
    title:       'Tous les matchs du club en direct',
    body:        'Scores en direct de toutes les équipes — même pendant votre propre match depuis la mi-temps. Résultats mis à jour en temps réel par vos coachs.',
    emoji:       '📡',
    why:         'Rester connecté à son club renforce l\'appartenance et la motivation.',
  },
  {
    id:          6,
    title:       'Rejoignez SportLink',
    body:        'Convocations, transport, résultats — gérez tout en un tap. Créez votre compte gratuitement.',
    emoji:       '⚽',
    isCTA:       true,
  },
];
