export const playerTour = [
  {
    id:    1,
    tab:   'home',
    action: null,
    title: 'Ton club en direct — 3 zones',
    body:  'L\'onglet Actus centralise tout. Zone 1 : tes convocations en attente de réponse. Zone 2 : le score EN DIRECT — FC SportLink Démo U17 mène 2-0 en ce moment. Zone 3 : les derniers résultats, annonces du staff, et covoiturages disponibles.',
    emoji: '⚽',
    why:   'Ton club publie ses infos ici en priorité, avant même Instagram ou Facebook.',
  },
  {
    id:          2,
    tab:         'home',
    action:      null,
    title:       'Ta convocation — réponds en 2 taps',
    body:        'Tu es convoqué pour le match vs US Bohars U17 ! Appuie sur [Présent] : un panneau s\'ouvre pour déclarer ton transport — "Je conduis", "Je cherche une place" ou "Par mes propres moyens". Le coach voit ta réponse et ton mode de transport immédiatement.',
    emoji:       '📋',
    target:      'convocation-respond',
    tryItAction: 'convocation-responded',
    tryItLabel:  'Répondre à la convocation',
    why:         'Le coach peut préparer sa tactique et sa composition dès que tu réponds.',
  },
  {
    id:       3,
    tab:      'map',
    action:   'focus-demo-event',
    position: 'top',
    title:    'Covoiturage pour le déplacement',
    body:     'Match à l\'extérieur ce weekend ? Propose une place dans ta voiture ou trouve un covoiturage en 2 taps. Plus besoin d\'organiser par WhatsApp.',
    emoji:    '🚗',
    tryItAction: 'carpool-requested',
    tryItLabel:  'Trouver un covoiturage',
    why:        'Le covoiturage via SportLink fonctionne aussi pour les joueurs sans permis.',
  },
  {
    id:     4,
    tab:    'mon-club',
    action: null,
    title:  'Ton équipe et l\'effectif',
    body:   'Retrouve la liste complète de tes coéquipiers, leurs postes et leurs statistiques. 75 joueurs dans le club, organisés par équipe.',
    emoji:  '👥',
    why:    'L\'effectif est mis à jour en temps réel par ton staff — toujours fidèle à la réalité.',
  },
  {
    id:          5,
    tab:         'home',
    action:      null,
    title:       'Sauvegarde tes matchs',
    body:        'Mets en favoris les matchs auxquels tu veux assister ou jouer. Tu recevras un rappel automatique la veille pour ne rien rater.',
    emoji:       '⭐',
    target:      'favorite-btn',
    tryItAction: 'event-favorited',
    tryItLabel:  'Sauvegarder un événement',
    why:         'Tu peux aussi voir les matchs des autres équipes du club — parfait pour supporter tes coéquipiers.',
  },
  {
    id:    6,
    tab:   'home',
    action: null,
    title: 'Rejoins SportLink',
    body:  'Crée ton compte gratuitement et connecte-toi au club dans toute sa dimension. Convocations, résultats, covoiturage — tout au même endroit.',
    emoji: '🚀',
    isCTA: true,
  },
];
