export const presidentTour = [
  {
    id:    1,
    tab:   'mon-club',
    action: null,
    title: 'Votre espace club',
    body:  'Bienvenue dans votre tableau de bord ! Ici vous gérez tout : événements, communication, statistiques. Le FC SportLink Démo est votre terrain d\'essai.',
    emoji: '🏟️',
    why:   'Tout ce dont un président a besoin est accessible en 1 à 2 taps depuis cet écran.',
  },
  {
    id:     2,
    tab:    'mon-club',
    action: 'scroll-to-events',
    title:  'Vos prochains événements',
    body:   'Retrouvez tous vos matchs, entraînements et tournois à venir. Un calendrier vivant, toujours à jour, accessible à vos 342 abonnés. Chaque publication notifie automatiquement vos abonnés.',
    emoji:  '📅',
    why:    'Vos abonnés consultent le calendrier en moyenne 3× par semaine avant un match.',
  },
  {
    id:          3,
    tab:         'mon-club',
    action:      'open-event-form',
    title:       'Créer un événement',
    body:        'En un clic, créez un match, un entraînement ou un tournoi. Vos 342 abonnés sont notifiés automatiquement. Essayez maintenant — c\'est votre premier acte de président !',
    emoji:       '➕',
    target:      'fab-add',
    tryItAction: 'event-created',
    tryItLabel:  'Créer un événement',
    why:         'Les clubs qui publient leurs événements à l\'avance ont 2× plus d\'affluence en tribunes.',
  },
  {
    id:          4,
    tab:         'mon-club',
    action:      'open-announcements',
    title:       'Publier une annonce',
    body:        'Envoyez des annonces ciblées par équipe : résultat de match, convocation urgente, infos pratiques. Chaque abonné reçoit une notification push dans les secondes qui suivent.',
    emoji:       '📢',
    tryItAction: 'announcement-sent',
    tryItLabel:  'Envoyer une annonce',
    why:         'Les annonces push ont un taux d\'ouverture de 85 % vs 20 % pour les emails.',
  },
  {
    id:          5,
    tab:         'mon-club',
    action:      'open-convocations',
    title:       'Gérer les convocations',
    body:        'Convoquez vos joueurs pour un match en quelques secondes. Chaque convoqué reçoit une notification push et peut confirmer directement — vous voyez les réponses en temps réel.',
    emoji:       '📋',
    target:      'convocations-tab',
    tryItAction: 'convocation-sent',
    tryItLabel:  'Envoyer une convocation',
    why:         'Les convocations via SportLink ont un taux de réponse de 89 % vs 60 % par WhatsApp.',
  },
  {
    id:     6,
    tab:    'mon-club',
    action: 'open-dashboard',
    title:  'Suivi des présences en direct',
    body:   'Dès qu\'un joueur répond à sa convocation, le compteur se met à jour en direct : X présents, Y absents, Z sans réponse. Vous composez votre équipe 48h à l\'avance.',
    emoji:  '✅',
    target: 'admin-dashboard',
    why:    'Connaître son effectif à l\'avance réduit le stress du jour J et améliore la performance collective.',
  },
  {
    id:          7,
    tab:         'mon-club',
    action:      'open-poster-studio',
    title:       'Créer une affiche pro',
    body:        'PosterStudio génère des affiches professionnelles pour vos matchs en quelques clics. 37 templates, 3 formats (story, carré, paysage). Choisissez un template, personnalisez, exportez en HD.',
    emoji:       '🎨',
    tryItAction: 'poster-generated',
    tryItLabel:  'Créer et télécharger une affiche',
    why:         'Les clubs avec des affiches pro gagnent en moyenne 40 % d\'abonnés en plus sur Instagram.',
  },
  {
    id:     8,
    tab:    'mon-club',
    action: 'close-overlay',
    title:  'Partager sur les réseaux',
    body:   'Depuis PosterStudio, partagez en un tap sur WhatsApp, Instagram et Facebook. Votre affiche touche directement vos supporters, parents et futurs abonnés.',
    emoji:  '📱',
    why:    'Un partage WhatsApp touche en moyenne 150 contacts dans un réseau de supporters local.',
  },
  {
    id:     9,
    tab:    'home',
    action: null,
    title:  'Votre cockpit en temps réel',
    body:   'L\'onglet Actus devient votre tableau de bord opérationnel : carte de match avant-match avec les réponses de convocation en direct, score live depuis le terrain, et raccourcis PosterStudio pour votre communicant.',
    emoji:  '⚡',
    target: 'coach-match-card',
    why:    'Toutes vos tâches urgentes du jour en un seul écran — sans chercher dans 4 onglets différents.',
  },
  {
    id:     9.5,
    tab:    'home',
    action: null,
    title:  'Le covoiturage intégré',
    body:   'Pour chaque match à l\'extérieur, les parents et joueurs peuvent proposer ou demander un covoiturage directement dans l\'app. Fini les groupes WhatsApp pour coordonner les trajets !',
    emoji:  '🚗',
    why:    'Le covoiturage intégré réduit les retards de 35 % et renforce la cohésion d\'équipe.',
  },
  {
    id:     10,
    tab:    'mon-club',
    action: 'open-dashboard',
    title:  'Statistiques détaillées',
    body:   'Suivez l\'engagement de votre communauté : vues de page, nouveaux abonnés, participations aux événements, affiches générées. Mesurez l\'impact réel de votre communication.',
    emoji:  '📊',
    target: 'admin-dashboard',
    why:    'Les stats permettent d\'identifier les meilleures heures pour publier vos annonces.',
  },
  {
    id:     11,
    tab:    'clubs',
    action: null,
    title:  'Votre page club publique',
    body:   'C\'est ainsi que vos supporters, joueurs et partenaires voient votre club. Une vitrine moderne avec votre agenda, vos résultats et vos sponsors — sans aucune compétence web requise.',
    emoji:  '🌐',
    why:    'Une page club soignée augmente le nombre d\'abonnements spontanés de 60 %.',
  },
  {
    id:    12,
    tab:   'mon-club',
    action: null,
    title: 'Prêt à créer votre club ?',
    body:  'Vous venez de voir les fonctionnalités essentielles de SportLink. Créez votre club gratuitement en 2 minutes et commencez à fédérer votre communauté dès aujourd\'hui !',
    emoji: '🚀',
    isCTA: true,
  },
];
