export const presidentTour = [
  {
    id:          1,
    title:       'Votre cockpit opérationnel',
    body:        'Bienvenue sur SportLink. Cet écran résume tout ce dont un président a besoin : Quick Actions, matchs en direct de toutes vos équipes, et fil d\'actualité complet du club.',
    emoji:       '👑',
    why:         'Un seul écran suffit pour piloter un club en temps réel.',
  },
  {
    id:          2,
    title:       'Ouvrez le menu d\'actions',
    body:        'Le bouton + au centre de la navigation donne accès à toutes les actions du club en un tap.',
    emoji:       '➕',
    clickTarget: 'fab-add',
    clickLabel:  'Bouton + en bas au centre',
  },
  {
    id:          3,
    title:       'Créez votre prochain événement',
    body:        'Sélectionnez "Créer un événement". Vos 342 abonnés seront notifiés automatiquement. Remplissez le formulaire et validez pour créer votre premier match !',
    emoji:       '📅',
    clickTarget: 'fab-event',
    clickLabel:  '"Créer un événement"',
    tryItAction: 'event-created',
    tryItLabel:  'Créer un événement',
    why:         'Les clubs qui publient leurs événements à l\'avance ont 2× plus d\'affluence en tribunes.',
  },
  {
    id:          4,
    title:       'Communiquez avec vos équipes',
    body:        'Depuis ce même menu, envoyez une annonce ciblée à toutes vos équipes ou à une seule. Résultat de match, convocation urgente, info pratique — en push en 2 secondes.',
    emoji:       '📢',
    closeOverlayBefore: true,
  },
  {
    id:          5,
    title:       'Ouvrez le menu à nouveau',
    body:        'Appuyez sur + pour accéder à l\'option d\'annonce.',
    emoji:       '➕',
    clickTarget: 'fab-add',
    clickLabel:  'Bouton + en bas au centre',
  },
  {
    id:          6,
    title:       'Envoyez une annonce ciblée',
    body:        'Sélectionnez "Envoyer une annonce". Choisissez votre type de message, rédigez, envoyez. 85% de taux d\'ouverture !',
    emoji:       '📢',
    clickTarget: 'fab-announce',
    clickLabel:  '"Envoyer une annonce"',
    tryItAction: 'announcement-sent',
    tryItLabel:  'Envoyer une annonce',
    why:         'Les annonces push ont un taux d\'ouverture de 85% vs 20% pour les emails.',
  },
  {
    id:          7,
    title:       'Convoquez vos joueurs en 3 taps',
    body:        'Sur la carte match, appuyez sur "Créer la convocation". Sélectionnez vos joueurs, validez — chaque convoqué reçoit une notification push instantanée.',
    emoji:       '📋',
    clickTarget: 'convocation-btn',
    clickLabel:  '"Créer la convocation"',
    tryItAction: 'convocation-sent',
    tryItLabel:  'Envoyer une convocation',
    why:         '89% de taux de réponse aux convocations vs 60% par WhatsApp.',
    closeOverlayBefore: true,
  },
  {
    id:          8,
    title:       'Votre agenda live',
    body:        'Retrouvez ici tous vos prochains matchs et entraînements dans l\'ordre chronologique avec les présences confirmées en temps réel.',
    emoji:       '📅',
  },
  {
    id:          9,
    title:       'Accédez à votre espace club',
    body:        'Appuyez sur l\'onglet "Mon Club" pour voir votre tableau de bord, modifier votre page et gérer l\'équipe.',
    emoji:       '🏛',
    clickTarget: 'tab-mon-club',
    clickLabel:  'Onglet "Mon Club"',
    closeOverlayBefore: true,
  },
  {
    id:          10,
    title:       'Tableau de bord et statistiques',
    body:        'Suivez l\'engagement de votre communauté : abonnés, vues de page, participations. Mesurez l\'impact réel de votre communication.',
    emoji:       '📊',
    clickTarget: 'admin-dashboard',
    clickLabel:  '"Tableau de bord"',
    why:         'Les clubs qui suivent leurs statistiques publient aux meilleures heures et gagnent 2× plus d\'abonnés.',
  },
  {
    id:          11,
    title:       'Votre page club publique',
    body:        'Appuyez sur l\'onglet "Clubs" pour voir comment vos supporters, joueurs et partenaires voient votre club.',
    emoji:       '🌐',
    clickTarget: 'tab-clubs',
    clickLabel:  'Onglet "Clubs"',
  },
  {
    id:          12,
    title:       'Prêt à créer votre club ?',
    body:        'Vous venez de découvrir les fonctionnalités essentielles de SportLink. Créez votre club gratuitement en 2 minutes et commencez à fédérer votre communauté !',
    emoji:       '🚀',
    isCTA:       true,
  },
];
