export const presidentTour = [
  {
    id:    1,
    tab:   'home',
    action: null,
    title: 'Votre cockpit opérationnel',
    body:  'Tout ce qu\'un président surveille en un seul écran. Zone 1 : Quick Actions (convocations, séances d\'entraînement). Zone 2 : matchs EN DIRECT de toutes vos équipes. Zone 3 : fil d\'actualité complet du club.',
    emoji: '👑',
    target: 'coach-match-card',
    why:   'Un seul écran suffit pour piloter un club en temps réel.',
  },
  {
    id:          2,
    tab:         'home',
    action:      'open-event-form',
    title:       'Créer votre prochain événement',
    body:        'Créez un match, un tournoi ou un entraînement en quelques taps. Vos 342 abonnés sont notifiés automatiquement. Essayez maintenant !',
    emoji:       '➕',
    target:      'fab-add',
    tryItAction: 'event-created',
    tryItLabel:  'Créer un événement',
    why:         'Les clubs qui publient leurs événements à l\'avance ont 2× plus d\'affluence en tribunes.',
  },
  {
    id:          3,
    tab:         'home',
    action:      'open-announcements',
    title:       'Publier une annonce ciblée',
    body:        'Résultat de match, convocation urgente, info pratique — ciblée par équipe. Chaque abonné reçoit une notification push dans les secondes qui suivent.',
    emoji:       '📢',
    tryItAction: 'announcement-sent',
    tryItLabel:  'Envoyer une annonce',
    why:         'Les annonces push ont un taux d\'ouverture de 85% vs 20% pour les emails.',
  },
  {
    id:          4,
    tab:         'home',
    action:      null,
    title:       'Convoquer vos joueurs en 3 taps',
    body:        'Cliquez "Créer la convocation" sur le match de votre choix. Sélectionnez vos joueurs, validez. Chaque convoqué reçoit une notification push et peut confirmer directement.',
    emoji:       '📋',
    target:      'coach-match-card',
    tryItAction: 'convocation-sent',
    tryItLabel:  'Envoyer une convocation',
    why:         '89% de taux de réponse aux convocations vs 60% par WhatsApp.',
  },
  {
    id:          5,
    tab:         'home',
    action:      'open-poster-studio',
    title:       'Créer une affiche pro en 2 minutes',
    body:        '37 templates professionnels, 3 formats (story, carré, paysage). Choisissez, personnalisez les couleurs et le texte, exportez en HD et partagez sur Instagram en un tap.',
    emoji:       '🎨',
    tryItAction: 'poster-generated',
    tryItLabel:  'Créer et télécharger une affiche',
    why:         'Les clubs avec des affiches pro gagnent en moyenne 40% d\'abonnés en plus sur Instagram.',
  },
  {
    id:     6,
    tab:    'home',
    action: null,
    title:  'Mon agenda — présences en un coup d\'œil',
    body:   'Chaque joueur, coach ou parent voit ici tous ses prochains matchs et entraînements dans l\'ordre chronologique. Il confirme sa présence en un tap — vous voyez les réponses en temps réel.',
    emoji:  '📅',
    target: 'agenda-section',
    why:    'Les clubs SportLink ont 89% de taux de réponse aux convocations vs 60% par WhatsApp.',
  },
  {
    id:     7,
    tab:    'mon-club',
    action: 'open-dashboard',
    title:  'Statistiques et tableau de bord',
    body:   'Suivez l\'engagement de votre communauté : abonnés, vues de page, participations aux événements, affiches générées. Identifiez vos meilleures publications et mesurez l\'impact réel de votre communication.',
    emoji:  '📊',
    target: 'admin-dashboard',
    why:    'Les clubs qui suivent leurs statistiques publient aux meilleures heures et gagnent 2× plus d\'abonnés.',
  },
  {
    id:     8,
    tab:    'clubs',
    action: null,
    title:  'Votre page club publique',
    body:   'C\'est ainsi que vos supporters, joueurs et partenaires voient votre club. Une vitrine moderne : agenda, résultats, sponsors, effectif — sans aucune compétence web requise.',
    emoji:  '🌐',
    why:    'Une page club soignée augmente le nombre d\'abonnements spontanés de 60%.',
  },
  {
    id:    9,
    tab:   'home',
    action: null,
    title: 'Prêt à créer votre club ?',
    body:  'Vous venez de voir les fonctionnalités essentielles de SportLink. Créez votre club gratuitement en 2 minutes et commencez à fédérer votre communauté dès aujourd\'hui !',
    emoji: '🚀',
    isCTA: true,
  },
];
