export const supporterTour = [
  {
    id:     1,
    tab:    'home',
    action: null,
    title:  'L\'actu de votre club en un seul endroit',
    body:   'Résultats, annonces, covoiturages, scores en direct — tout le club sans chercher sur 5 réseaux différents. Le fil d\'actualité se met à jour en temps réel.',
    emoji:  '🏟️',
    target: 'live-multiplex',
    why:    'Les supporters SportLink sont informés 3× plus vite que les non-abonnés.',
  },
  {
    id:          2,
    tab:         'clubs',
    action:      null,
    title:       'Suivre votre club',
    body:        'Un tap suffit pour s\'abonner. Vous recevez ensuite chaque résultat, annonce et convocation urgente directement en notification push — sans rater un seul but.',
    emoji:       '💙',
    target:      'follow-club-btn',
    tryItAction: 'club-followed',
    tryItLabel:  'Suivre le club',
    why:         'Les supporters abonnés assistent à 2× plus de matchs que les non-abonnés.',
  },
  {
    id:          3,
    tab:         'home',
    action:      null,
    title:       'Sauvegardez les matchs qui vous tiennent à cœur',
    body:        'Marquez vos matchs en favoris pour les retrouver en un instant. Vous recevez un rappel la veille et le jour J — plus jamais de match raté.',
    emoji:       '⭐',
    target:      'favorite-btn',
    tryItAction: 'event-favorited',
    tryItLabel:  'Ajouter un match aux favoris',
    why:         'Les supporters qui sauvegardent les matchs y assistent 2× plus souvent.',
  },
  {
    id:     4,
    tab:    'home',
    action: null,
    title:  'Toutes les équipes en direct simultanément',
    body:   'Équipe 1, Réserve, U17, Féminines — suivez tous les matchs du club en même temps depuis un seul écran. Scores mis à jour en temps réel par les coachs sur le terrain.',
    emoji:  '📡',
    target: 'live-multiplex',
    why:    'Restez connecté à 100% de votre club, même quand vous ne pouvez pas vous déplacer.',
  },
  {
    id:    5,
    tab:   'home',
    action: null,
    title: 'Rejoignez SportLink',
    body:  'Suivez votre club comme jamais. Résultats en direct, annonces push, matchs sauvegardés — tout gratuitement.',
    emoji: '🏟️',
    isCTA: true,
  },
];
