export const supporterTour = [
  {
    id:          1,
    title:       'L\'actu de votre club en temps réel',
    body:        'Résultats, annonces, covoiturages, scores en direct — tout le club sans chercher sur 5 réseaux différents. Le fil d\'actualité se met à jour en temps réel.',
    emoji:       '🏟️',
    why:         'Les supporters SportLink sont informés 3× plus vite que les non-abonnés.',
  },
  {
    id:          2,
    title:       'Scores en direct de toutes les équipes',
    body:        'Équipe 1, Réserve, U17, Féminines — suivez tous les matchs simultanément depuis un seul écran. Pas besoin de rafraîchir — c\'est en direct.',
    emoji:       '📡',
    why:         'Restez connecté à 100% de votre club, même quand vous ne pouvez pas vous déplacer.',
  },
  {
    id:          3,
    title:       'Découvrez la page du club',
    body:        'Appuyez sur l\'onglet Clubs pour voir la vitrine complète du club : agenda, résultats, effectif, sponsors.',
    emoji:       '💙',
    clickTarget: 'tab-clubs',
    clickLabel:  'Onglet "Clubs"',
  },
  {
    id:          4,
    title:       'Suivez votre club',
    body:        'Un tap suffit pour s\'abonner. Vous recevrez chaque résultat, annonce et convocation urgente en notification push — sans rater un seul but.',
    emoji:       '💙',
    clickTarget: 'follow-club-btn',
    clickLabel:  'Bouton "Suivre"',
    tryItAction: 'club-followed',
    tryItLabel:  'Suivre le club',
    why:         'Les supporters abonnés assistent à 2× plus de matchs que les non-abonnés.',
  },
  {
    id:          5,
    title:       'Revenez sur le fil d\'actualité',
    body:        'Appuyez sur l\'onglet Accueil pour retrouver le fil avec les matchs à sauvegarder.',
    emoji:       '⭐',
    clickTarget: 'tab-home',
    clickLabel:  'Onglet "Accueil"',
  },
  {
    id:          6,
    title:       'Sauvegardez les matchs à ne pas rater',
    body:        'Appuyez sur l\'étoile ⭐ d\'un match pour le sauvegarder. Vous recevrez un rappel la veille et le jour J — plus jamais de match raté.',
    emoji:       '⭐',
    clickTarget: 'favorite-btn',
    clickLabel:  'Étoile ⭐ du match',
    tryItAction: 'event-favorited',
    tryItLabel:  'Ajouter un match aux favoris',
    why:         'Les supporters qui sauvegardent les matchs y assistent 2× plus souvent.',
  },
  {
    id:          7,
    title:       'Rejoignez SportLink',
    body:        'Suivez votre club comme jamais. Résultats en direct, annonces push, matchs sauvegardés — tout gratuitement.',
    emoji:       '🏟️',
    isCTA:       true,
  },
];
