export const supporterTour = [
  {
    id:    1,
    tab:   'clubs',
    action: null,
    title: 'Découvrez les clubs sportifs',
    body:  'Explorez tous les clubs autour de vous. Football, basket, handball, rugby... Chaque club a sa page avec son agenda, ses résultats et son actualité.',
    emoji: '🏟️',
    why:   'Plus de 7 000 clubs sportifs bretons. Trouvez le vôtre et ne ratez plus aucun match.',
  },
  {
    id:          2,
    tab:         'clubs',
    action:      null,
    title:       'Suivre le FC SportLink Démo',
    body:        'Abonnez-vous à un club et recevez toutes ses actualités. Résultats, affiches, annonces — directement en notification push sur votre téléphone.',
    emoji:       '❤️',
    target:      'follow-club-btn',
    tryItAction: 'club-followed',
    tryItLabel:  'Suivre ce club',
    why:         'Les abonnés reçoivent les résultats en push dans les 5 minutes après le coup de sifflet final.',
  },
  {
    id:    3,
    tab:   'home',
    action: null,
    title: 'Live, résultats et annonces en un scroll',
    body:  'Zone 2 : badge 🔴 EN DIRECT avec les scores de tous les matchs en cours — FC SportLink Démo U17 mène 2-0 en ce moment. Zone 3 : le ClubFeed avec résultats, affiches, annonces du staff et covoiturages disponibles. Tout le club en un seul écran.',
    emoji: '📰',
    why:   'Un seul endroit pour suivre toutes les équipes du club, des seniors aux féminines.',
  },
  {
    id:    4,
    tab:   'home',
    action: null,
    title: 'Les prochains matchs',
    body:  'Consultez tous les matchs à venir avec lieu, horaire et adversaire. Cliquez sur un match pour voir les affiches, les compositions et les covoiturages disponibles.',
    emoji: '📅',
    why:   'Planifiez vos déplacements en tribune plusieurs semaines à l\'avance.',
  },
  {
    id:    5,
    tab:   'home',
    action: null,
    title: 'Rejoignez SportLink',
    body:  'Créez votre compte gratuitement et rejoignez la communauté SportLink. Suivez vos clubs favoris, réagissez aux résultats et restez connecté au sport local.',
    emoji: '🚀',
    isCTA: true,
  },
];
